# Site settings
title: 'Software Engineers Blog - CurryWurst'
description: 'Along with the lecture "Introduction to Software Engineering for Engineers" at Otto-von-Guericke University Magdeburg, our team "CurryWurst"
	will develop an "Activity Monitoring" app for Android operating systems. This blog will be regularly updated to keep you up to date about our progress.
	Have fun following our work ;)'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/TestRepo'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'CurryWurst'
  github_username:  joshgerdes
  
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 6
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
